version: '2'
services:
  consul:
    image: consul
    container_name: consul
    ports:
      - '127.0.0.1:8500:8500'
    command: agent -dev -client 0.0.0.0

  registrator:
    image: gliderlabs/registrator
    container_name: registrator
    command: -internal consul://127.0.0.1:8500
    network_mode: host
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock

  proxy:
    image: phylor/haproxy-consul
    container_name: proxy
    environment:
      CONSUL_CONNECT: localhost:8500
      HAPROXY_USESSL: force
      LETSENCRYPT_PORT: 9999
    expose:
      - 80
      - 443
    network_mode: host
    volumes:
      - tls-certificates:/certs

  letsencrypt:
    image: phylor/letsencrypt-consul
    container_name: letsencrypt
    network_mode: host
    environment:
      CONSUL_CONNECT: localhost:8500
      FQDN: "{{ ansible_fqdn }}"
      EMAIL: "{{ email }}"
    volumes:
      - tls-certificates:/certificates
      - letsencrypt-etc:/etc/letsencrypt

volumes:
  tls-certificates: {}
  letsencrypt-etc: {}
